dbt_upstart:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: upstart-technical-project
    dataset: dummy
    threads: 1
    timeout_seconds: 300
    location: US