name: Deploy DAGs to Composer

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: upstart-technical-project
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy DAGs and data folders to Composer GCS bucket
        run: |
          gsutil cp airflow_dbt/dags/*.py gs://composer-upstart/dags
          gsutil -m cp -r airflow_dbt/data/* gs://composer-upstart/data
          gsutil -m cp -r airflow_dbt/plugins/* gs://composer-upstart/plugins
