name: Deploy DAGs to Composer

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: upstart-tech-test
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy DAGs to Composer GCS bucket
        run: |
          gsutil cp airflow_dbt/dags/*.py gs://us-central1-airflow-upstart-d3f60ca0-bucket/dags/